# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AutomateGraphModelerl
                                 A QGIS plugin
 This plugin automate the graphical modeller 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-10-20
        copyright            : (C) 2023 by DMN SOLUTIONS
        email                : michel.nzikou@alumni.uleth.ca
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AutomateGraphModelerl class from file AutomateGraphModelerl.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .automate_graph_modeller import AutomateGraphModelerl
    return AutomateGraphModelerl(iface)
